spring:
  application:
    name: employee-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /employee-management-service
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches,cache
  endpoint:
    health:
      show-details: always
    cache:
      enabled: true

logging:
  level:
    root: INFO
    com.enterprise.employeeservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
